import { Injectable } from '@angular/core';
import { Game } from '../model/game';

@Injectable({
  providedIn: 'root'
})
export class GameService {
  private games = new Array<Game>();
  private autoGeneratedId = 0;


  constructor() { }

  save() {
    localStorage.setItem('games', JSON.stringify(this.games));
    localStorage.setItem('gamesAutoGeneratedId', this.autoGeneratedId.toString());

  }

  load() {
    this.games = JSON.parse(localStorage.getItem('games'));

    if (this.games == null) {
      this.games = new Array<Game>();
    }

    const autoId = localStorage.getItem('gamesAutoGeneratedId');

    if (autoId) {
      this.autoGeneratedId = Number(autoId);
    }
  }

  insert(game: Game) {
    game.id = this.autoGeneratedId;
    this.games.push(game);
    this.autoGeneratedId++;
    this.save();

  }

  list(): Array<Game> {
    this.load();
    return this.games;

  }

  remove(id: number) {
    for (let i = 0; i < this.games.length; i++) {
      const m = this.games[i];
      if (m.id === id) {
        this.games.splice(i, 1);
        break;
      }
    }
  }

  update(game: Game) {
    for (let i = 0; i < this.games.length; i++) {
      const g = this.games[i];
      if (g.id === game.id) {
        this.games[i] = game;
        break;
      }
    }
  }


}
